#!/bin/ksh

#
# Sets up appropriate ENV variables for running MEI in Production.
#
# All SQL transactions logged to USERLOG.
#

unset TERM
export APP USERLOG DSQUERY MGD STRAINS NOMEN INSTALL_ROOT
export SYBASE OPENWINHOME PYTHONPATH
export XKEYSYMDB TeleUSE XNLSPATH XUSERFILESEARCHPATH LD_LIBRARY_PATH PATH
export EIREPORTDIR EIARCHIVEDIR EIWITHDRAWALDIR EIBREAKSPLITDIR
export EIDEBUG

APP=gxd
EIDEBUG=1

cd `dirname $0`
INSTALL_ROOT=`pwd`

OPENWINHOME=/usr/openwin
XKEYSYMDB=$OPENWINHOME/lib/XKeysymDB
PYTHONPATH=/usr/local/mgi/lib/python:/usr/local/etc/httpd/python

USERLOG=$HOME/.gxd_dev-log

DSQUERY=MGD_DEV
MGD=mgd_release
STRAINS=strains_dev
NOMEN=nomen_dev

EIREPORTDIR=$HOME/mgireport
EIARCHIVEDIR=$INSTALL_ROOT/mgireport
EIWITHDRAWALDIR=$EIARCHIVEDIR/withdrawals
EIBREAKSPLITDIR=$EIARCHIVEDIR/breakpointsplits

SYBASE=/opt/sybase
TeleUSE=/opt/teleuseXRT
XNLSPATH=$TeleUSE/X11R5/lib/nls
XUSERFILESEARCHPATH=%N:$OPENWINHOME/lib/app-defaults/%L/%N:$OPENWINHOME/lib/app-defaults/%N:$TeleUSE/appl_res/%L/%N:$TeleUSE/appl_res/%N:/usr/lib/X11/app-defaults/%L/%N:/usr/lib/X11/app-defaults/%N

LD_LIBRARY_PATH=$SYBASE/lib:$TeleUSE/lib:$OPENWINHOME/lib:/usr/lib:/usr/ucblib
PATH=$PATH:$OPENWINHOME/bin:$TeleUSE/bin:$SYBASE/bin:/usr/ucb:/usr/local/bin

umask 022

exec $APP >> $USERLOG
