
/**************************************************************
 *
 * Name: uxb_main.c
 *
 *   File was generated by TeleUSE tool 'uxb_gmain'
 *   -mode pcd
 *
 **************************************************************/

#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#include <teleuse/teleuse.h>
#include <teleuse/tu_util.h>
#include <teleuse/tu_arg.h>
#include <teleuse/tu_string.h>
#include <teleuse/tk_widgets.h>
#include <teleuse/tu_event.h>
#include <drut/dr_dbcom.h>
#include <drut/dr_dcomp.h>
#include <X11/Xlib.h>
#include <X11/Intrinsic.h>

#ifdef _NO_PROTO
extern int uxb_mainc_init();
#else
#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
extern int uxb_mainc_init(int*, char **, int, char*);
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
#endif /* _NO_PROTO */



/****************************************************************
 * base:
 ****************************************************************/
#ifdef _NO_PROTO
static char *base(str)
     char *str;
#else
static char *base(char *str)
#endif /* _NO_PROTO */
{
  static char basename[1024];
  char *p;

  if (p = strrchr(str, '/'))
    (void) strcpy(basename, p+1);
  else
    (void) strcpy(basename, str);
  if (p = strrchr(basename, '.'))
    *p ='\0';
  return basename;
}


/**************************************************************
 * component_init:
 **************************************************************/
#ifdef _NO_PROTO
static int component_init(argc, argv, phase)
     int* argc;
     char** argv;
     int phase;
#else
static int component_init(int* argc, char** argv, int phase)
#endif /* _NO_PROTO */
{
  char* uidef_file;
  uidef_file = 0;
  if (phase == 1) {
    if (tu_get_arg(argc, argv, (char*)"-uidef", True, &uidef_file))
      uidef_file = tu_strdup(uidef_file);
    else if (uidef_file = tu_find_file((char*)"gxd.ui", 0)) ;
    else
      uidef_file = tu_find_file((char*)"/home/lec/mgi/ei-trunk/gxd/gxd.ui", 0);
  }

  if (uxb_mainc_init(argc,argv,phase,uidef_file)) return 1;
  return 0;
}


/**************************************************************
 * main:
 **************************************************************/
#ifdef _NO_PROTO
int main(argc, argv)
     int argc;
     char** argv;
#else
int main(int argc, char** argv)
#endif /* _NO_PROTO */
{
  Display     * display;
  char          aclass[132];
  char          name[132];
  int           n = 0;
  Arg           args[2];
  char **temp_argv = argv;
  char        * logf;
  tu_status_t   lstatus;
  char        * dbug_name = 0;
  tu_boolean    dbug_halt;

  /* store a copy for the runtime */
  tu_set_arg_handler(argc, argv);

  /* set stdout explicitly line-buffered */
  tu_line_buffer();

  strncpy(name, base(argv[0]), sizeof(name)-1);

  /* handle the '-name' option */
  while (*temp_argv) {
    if (!strcmp(*temp_argv, "-name")) {
      strncpy(name, *++temp_argv, sizeof(name)-1);
      break;
    }
    temp_argv++;
  }

  aclass[sizeof(aclass)-1] = '\0';
  strncpy(aclass, "GXD", sizeof(aclass)-1);

  tu_application_name  = name;
  tu_application_class = aclass;

  /* handle the '-v' option */
  if (tu_get_arg(&argc, argv, (char*)"-v", tu_false, 0)) {
    tu_verbose_flag = tu_true;
    (void) printf("***\n");
    (void) printf("*** %s\n", tu_get_release());
    (void) printf("***\n");
  }

  /* handle the '-log' option */
  if (tu_get_arg(&argc, argv, (char*)"-log", tu_false, 0))
    tu_open_log_file((char*)0, &lstatus);

  /* handle the '-logf' option */
  if (tu_get_arg(&argc, argv, (char*)"-logf", tu_true, &logf))
    tu_open_log_file(logf, &lstatus);

  /* Get D debugger information */
  (void)tu_get_arg(&argc, argv, (char*)"-dbug", tu_true, &dbug_name);
  if (!dbug_name)
    dbug_name = tu_application_name;
  dbug_halt = tu_get_arg(&argc, argv, (char*)"-hlt", tu_false, 0);

  /* For benefit of some C functions */
  tu_setup_locale();

  (void)component_init(&argc,argv,0);

  /* Initialize the X Toolkit Intrinsics */
  XtToolkitInitialize();

  /* Set up language environment for X */
  XtSetLanguageProc(0, 0, 0);

  /* Get an application context */
  tu_global_app_context = XtCreateApplicationContext();

  /* Get one display connection */
  display = XtOpenDisplay(tu_global_app_context,
                          0,
                          name, aclass,
                          (XrmOptionDescRec *)0, 0,
                          &argc, argv);
  if (!display) {
    (void) fprintf(stderr, "Unable to open display\n");
    exit(1);
  }

  /* remember this display */
  tu_disp_set_dpy((char*)"Display1", 0, display);

  /* prepare the argc/argv for top node */
  XtSetArg(args[n], XtNargc, argc); n++;
  XtSetArg(args[n], XtNargv, argv); n++;

  tu_global_top_widget =
    XtAppCreateShell(name, aclass,
                     applicationShellWidgetClass,
                     display, args, n);

  /* Initialize all toolkit classes */
  tu_initialize_interface();

  (void)component_init(&argc,argv,1);

  /* Instantiate all D modules */
#if !defined(_NOT_DEBUGGABLE_)
  dr_setup_dbug_connection(display, dbug_name);
  if (dbug_halt)
    tu_set_halt();
#endif
  tu_instantiate_modules();

  /* Enable dispatch of TeleUSE events */
  tu_start_dispatch();

  /* Start application event loop */
  XtAppMainLoop(tu_global_app_context);

  /*NOTREACHED*/
  return 0;
}

