#!/bin/csh -f

#
# Builds all EI apps as compiled applications
# (as is typically done prior to a release). 
#
# Progress of build is sent to stdout and a logfile.
#
# Usage: buildall 
# 
# Assumes: Must be executed in the same directory as the application
#          target directories, mgd, gxd, etc. 
#
# Output: buildall.log contains report of stdout and stderr messages

source ./Configuration

setenv LOG `pwd`/buildall.log

rm -f $LOG

foreach app ($EIAPPS)
   echo "BUILDING $app"
   buildapp $app compiled | tee >>& $LOG
end

