#!/bin/csh -f

#
# Builds a TeleUSE app using uxb.conf. 
#
# Usage:
#
#	buildapp applicationdirectory [compiled] 
#
# Where 'compiled' specifies that a compiled application should be built.
# Without this option, D modules are interpreted, which allows use of 
# the TeleUSE debugger. 

source ./Configuration

setenv EIAPP	$1
setenv MODE	$2

setenv LOG      ${EIINSTALLDIR}/buildapp${EIAPP}.log
rm -rf ${LOG}

date > ${LOG}

switch ("$MODE")
	case compiled:	
			setenv OPTIONS "-dmode compiled"
			breaksw
	default:	
			setenv OPTIONS ""
			breaksw
endsw

#
# uxb.conf is assumed...
#

cd $EIAPP
uxb $OPTIONS
