#!/bin/csh

#
# Cleans a TeleUSE Application using uxb.conf. 
#
# Usage:
#
#	cleanapp applicationdirectory
#

source Configuration

setenv EIAPP	$1
setenv REMFILES	"*.o *.c *.do *.ui cderes*"

cd $EIAPP
uxb clean
rm -f $REMFILES $EIAPP
cd ..
