#!/bin/csh -f

#
# Installs all EI apps as non-compiled applications
#
# Usage: install_linux_dev
#
# Output: install_linux_dev.log
#

source ./Configuration

setenv SYBASE /opt/sybase/15.7
setenv LD_LIBRARY_PATH ${SYBASE}/OCS-15_0/lib:${TeleUSE}/lib:${TeleUSE}/XRT/lib-shared:${TeleUSE}/conf/lib

setenv LOG $0.log
rm -f $LOG

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
uxb -destdir ${EIINSTALLDIR}/${EIAPP} install >>& ${LOG}
cd ..

date >> ${LOG}

end

