#!/bin/csh

#
# Builds (if necessary) and installs a compiled/interpreted version of 
# application using uxb.conf.
#
# Usage:
#
#	installapp applicationdirectory [compiled]
#
# if 'compiled' is given as an argument, then the application is installed 
# as a compiled application, rather than an interpreted D app.
#

source ./Configuration

setenv EIAPP	$1
setenv MODE	$2

switch ("$MODE")
	case compiled:	
			setenv OPTIONS "-dmode compiled"
			breaksw
	default:	
			setenv OPTIONS ""
			breaksw
endsw

#
# uxb.conf is assumed...
#

# create the application directory if it isn't already there
mkdir ${EIINSTALLDIR} >& /dev/null
mkdir ${EIINSTALLDIR}/${EIAPP} >& /dev/null

cd ${EIAPP}
uxb $OPTIONS -destdir ${EIINSTALLDIR}/${EIAPP} install
cd ..

#
# Copy main files to installation directory
#
cp Configuration ${EIINSTALLDIR}
cp runapp ${EIINSTALLDIR}
