#!/bin/csh -f

#
# Create sym-links for proper sybase/postgres versions
#

# link to the proper include file
cd ${EIBUILDDIR}/include
rm -rf dblib.h
ln -s ${EIINCLUDE} dblib.h
cd ${EIBUILDDIR}

#link to the proper csrc/mgisql.c
cd ${EIBUILDDIR}/csrc
rm -rf mgisql.c
ln -s ${EICSQL} mgisql.c
cd ${EIBUILDDIR}

#link to the proper csrc/mgilib.c
cd ${EIBUILDDIR}/csrc
rm -rf mgilib.c
ln -s ${EICLIB} mgilib.c
cd ${EIBUILDDIR}

#link to the proper dsrc/SQL.d file
cd ${EIBUILDDIR}/dsrc
rm -rf SQL.d
ln -s ${EIDSQL} SQL.d
cd ${EIBUILDDIR}

#link to the proper dsrc/DateLib.d file
cd ${EIBUILDDIR}/dsrc
rm -rf DateLib.d
ln -s ${EIDDATELIB} DateLib.d
cd ${EIBUILDDIR}

