#!/bin/csh -f

#
# Installs all EI apps as non-compiled applications
#
# Usage: install_pg_dev
#
# Output: install_pg_dev.log
#

source ./Configuration

setenv LOG $0.log
rm -f $LOG

#foreach app ($EIAPPS)
foreach app ("gxd")

echo "INSTALLING $app"
setenv EIAPP $app

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
uxb uxb_pg.conf clean >>& ${LOG}
rm -rf *.o *.c *.do *.ui cderes* ${EIAPP} *.log >>& ${LOG}
uxb uxb_pg.conf >>& ${LOG}
cd ..

date >> ${LOG}

end

