#!/bin/csh -f

#
# Installs all EI apps as non-compiled applications
#
# Usage: install_solaris_dev
#
# Output: install_solaris_dev.log
#

source ./Configuration

setenv SYBASE /opt/sybase/12.5
setenv LD_LIBRARY_PATH /opt/sybase/12.5/ASE-12_5/lib:/opt/sybase/12.5/OCS-12_5/lib:/usr/lib:/usr/local/lib:/usr/ucblib:/usr/openwin/lib:/usr/local/postgres/lib:/opt/teleuseXRT/lib:/opt/teleuseXRT/conf/lib

setenv LOG $0.log
rm -f $LOG

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
rm -rf *.do *.c *.o
uxb uxb_solaris clean
uxb uxb_solaris.conf -destdir ${EIINSTALLDIR}/${EIAPP} install >>& ${LOG}
cd ..

date >> ${LOG}

end

