#!/bin/csh -f

#
# Installs all EI apps as compiled applications
#
# Usage: install_solaris
#
# Output: install_solaris.log
#

source ./Configuration

setenv LOG $0.log
rm -f $LOG

setenv OPTIONS "-dmode compiled"

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

# create the application directory if it isn't already there

if ( ! -d ${EIINSTALLDIR}/${EIAPP} ) then
	mkdir -p ${EIINSTALLDIR}/${EIAPP}
endif

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
uxb uxb_solaris.conf ${OPTIONS} -destdir ${EIINSTALLDIR}/${EIAPP} install >>& ${LOG}
cd ..

#
# Copy main files to installation directory
#

if ( ! -f ${EIINSTALLDIR}/Configuration ) then
	cp Configuration ${EIINSTALLDIR}
endif

if ( ! -f ${EIINSTALLDIR}/runapp ) then
	cp runapp ${EIINSTALLDIR}
endif

date >> ${LOG}

end

