#!/bin/csh -f

#
# Installs all EI apps as compiled applications
#
# Usage: install_solaris
#
# Output: install_solaris.log
#

source ./Configuration

setenv SYBASE /opt/sybase/12.5
setenv LD_LIBRARY_PATH /opt/sybase/12.5/ASE-12_5/lib:/opt/sybase/12.5/OCS-12_5/lib:/usr/lib:/usr/local/lib:/usr/ucblib:/usr/openwin/lib:/usr/local/postgres/lib:/opt/teleuseXRT/lib:/opt/teleuseXRT/conf/lib

setenv LOG $0.log
rm -f $LOG

setenv OPTIONS "-dmode compiled"

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

# create the application directory if it isn't already there

if ( ! -d ${EIINSTALLDIR}/${EIAPP} ) then
	mkdir -p ${EIINSTALLDIR}/${EIAPP}
endif

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
uxb uxb_solaris clean
uxb uxb_solaris.conf ${OPTIONS} -destdir ${EIINSTALLDIR}/${EIAPP} install >>& ${LOG}
cd ..

#
# Copy main files to installation directory
#

rm -rf ${EIINSTALLDIR}/Configuration
rm -rf  ${EIINSTALLDIR}/runapp
cp Configuration ${EIINSTALLDIR}
cp runapp ${EIINSTALLDIR}

date >> ${LOG}

end

