#!/bin/csh -f

#
# Program: Install
#
# Original Author: Lori Corbani
#
# Purpose: To install the EI
#
# Modification History:
#
# 07/11/2006	lec
#	- new
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${EIINSTALLDIR} ) then
	mkdir ${EIINSTALLDIR}
endif

setenv LOG `pwd`/installall.log
rm -f $LOG

foreach app ($EIAPPS)
   echo "INSTALLING $app"
   installapp $app >>& $LOG
end

