#!/bin/csh -f -x

#
# Program: Install
#
# Original Author: Lori Corbani
#
# Purpose: To install the EI
#
# Modification History:
#
# 07/11/2006	lec
#	- new
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${EIINSTALLDIR} ) then
	mkdir ${EIINSTALLDIR}
endif

if ( ! -d ${EIWITHDRAWALDIR} ) then
	mkdir ${EIWITHDRAWALDIR}
endif

if ( ! -d ${EINLMDIR} ) then
	mkdir ${EINLMDIR}
endif

./installall compiled

