#!/bin/csh

#
# Installs all EI apps as compiled applications
# Progress of install is sent to stdout and a logfile.
#
# Assumes: Must be executed in the same directory as the application 
#          target directories, mgd, gxd, etc.
# 
# Usage: installall
#
# Output: installall.log contains report of stdout and stderr messages
#

source ./Configuration

setenv LOG `pwd`/installall.log
rm -f $LOG

foreach app ($EIAPPS)
   echo "INSTALLING $app"
   installapp $app compiled | tee >>& $LOG
end

