#!/bin/csh -f

#
# Installs all EI apps as non-compiled applications
#
# Usage: install_linux_dev
#
# Output: install_linux_dev.log
#

source ./Configuration

setenv LOG $0.log
rm -f $LOG

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

date > ${LOG}

#
# uxb.conf is assumed...
#

cd ${EIAPP}
uxb uxb_linux.conf clean >>& ${LOG}
rm -rf *.o *.c *.do *.ui cderes* ${EIAPP}
uxb uxb_linux.conf ${OPTIONS} >>& ${LOG}
cd ..

date >> ${LOG}

end

