#!/bin/csh -f

#
# Installs all EI apps as non-compiled applications
#
# Usage: install_linux
#
# Output: install_linux.log
#

source ./Configuration

setenv LOG $0.log
rm -f $LOG

# run configuration to set proper sybase/postgres symlinks
${EIBUILDDIR}/install_config

foreach app ($EIAPPS)

echo "INSTALLING $app"
setenv EIAPP $app

date > ${LOG}

cd ${EIAPP}
uxb uxb_linux.conf clean >>& ${LOG}
rm -rf *.o *.c *.do *.ui cderes* ${EIAPP} *.log >>& ${LOG}
uxb -dmode compiled uxb_linux.conf >>& ${LOG}
cd ..

date >> ${LOG}

end

