#!/bin/csh

#
# Builds (if necessary) and installs a compiled/interpreted version of 
# application using uxb.conf.
#
# Usage:
#
#	installapp applicationdirectory [compiled]
#
# if 'compiled' is given as an argument, then the application is installed 
# as a compiled application, rather than an interpreted D app.
#

source ./Configuration

setenv EIAPP	$1
setenv MODE	$2

setenv LOG	${EIINSTALLDIR}/install${EIAPP}.log
rm -rf ${LOG}

date > ${LOG}

switch ("${MODE}")
	case compiled:	
			setenv OPTIONS "-dmode compiled"
			breaksw
	default:	
			setenv OPTIONS ""
			breaksw
endsw

#
# uxb.conf is assumed...
#

# create the application directory if it isn't already there

if ( ! -d ${EIINSTALLDIR}/${EIAPP} ) then
	mkdir ${EIINSTALLDIR}/${EIAPP}
endif

cd ${EIAPP}
uxb ${OPTIONS} -destdir ${EIINSTALLDIR}/${EIAPP} install | tee -a ${LOG}
cd ..

#
# Copy main files to installation directory
#
cp Configuration ${EIINSTALLDIR}
cp runapp ${EIINSTALLDIR}

date > ${LOG}
