#!/bin/csh -f

#
# Sets up appropriate ENV variables for running MEI
#
# All SQL transactions logged to USERLOG.
#

setenv EIAPP	$1

cd `dirname $0`

source ./Configuration

cd $EIINSTALLDIR/$EIAPP
exec $EIAPP >>& $USERLOG
