#!/bin/csh -f

#
# Sets up appropriate ENV variables for running MEI
#
# All SQL transactions logged to USERLOG.
#

setenv EIAPP	$1

cd `dirname $0`

unsetenv MGICONFIG
source ./Configuration

cd ${EIBUILDDIR}/${EIAPP}
${EIAPP} >>& ${USERLOG}
