#!/bin/csh

#
# Runs statistics
#

cd `dirname $0` && source ../Configuration

${EIINSTALLDIR}/mgd/statistics.py -S${DSQUERY} -D${MGD} -U${DBUSER} -P${DBPASSWORDFILE} -mCR -e-2
${EIINSTALLDIR}/mgd/statistics.py -S${DSQUERY} -D${MGD} -U${DBUSER} -P${DBPASSWORDFILE} -mRI -e-2

