#!/bin/csh

#
# Runs statistics
#

cd `dirname $0` && source ../Configuration

${EIINSTALLDIR}/mgd/statistics.py -S${MGD_DBSERVER} -D${MGD_DBNAME} -U${MGD_DBUSER} -P${MGD_DBPASSWORDFILE} -mCR -e-2
${EIINSTALLDIR}/mgd/statistics.py -S${MGD_DBSERVER} -D${MGD_DBNAME} -U${MGD_DBUSER} -P${MGD_DBPASSWORDFILE} -mRI -e-2

