#!/bin/sh
#
# Builds (if necessary) and installs a compiled/interpreted version of 
# application using uxb.conf.
#
# Usage:
#
#	installapp [compiled]
#
# if 'compiled' is given as an argument, then the application is installed 
# as a compiled application, rather than an interpreted D app.
#
# Assumes:  EIINSTALLDIR has been set to an existing directory that will 
#           contain the various EI applications, or it is the null string (or
#           not defined. That is, if EIINSTALLDIR=/usr/local/mgi/ei, then 
#           it is assumed that $EIINSTALLDIR/app is the destination. If it 
#           is unset

APP=$1

if [ "$EIINSTALLDIR" = "" ]
then
	echo "Environment variable EIINSTALLDIR has not been defined."
	echo "It should be set to the parent directory of the EI applications." 
    exit 1
fi

if [ "$APP" != "" ]
then
	case "$APP" in
		compiled) OPTIONS="-dmode compiled"
			break;;
		*)    echo "Usage: $0 [compiled]"; exit 1; break;;
	esac
else
	OPTIONS=""
fi

#
# uxb.conf is assumed...
#

# create the mgi directory if it isn't already there
mkdir $EIINSTALLDIR/mgi >/dev/null 2>&1

uxb $OPTIONS -destdir $EIINSTALLDIR/mgi install
