#!/bin/ksh

#
# Sets up appropriate ENV variables for running MEI in Production.
#
# All SQL transactions logged to USERLOG.
#

unset TERM
export APP USERLOG INSTALL_ROOT
export OPENWINHOME
export XKEYSYMDB TeleUSE XNLSPATH XUSERFILESEARCHPATH LD_LIBRARY_PATH PATH

APP=mgi
EIDEBUG=0

cd `dirname $0`
INSTALL_ROOT=`pwd`

OPENWINHOME=/usr/openwin
XKEYSYMDB=$OPENWINHOME/lib/XKeysymDB

USERLOG=$HOME/.mgi-log

TeleUSE=/opt/teleuseXRT
XNLSPATH=$TeleUSE/X11R5/lib/nls
XUSERFILESEARCHPATH=%N:$OPENWINHOME/lib/app-defaults/%L/%N:$OPENWINHOME/lib/app-defaults/%N:$TeleUSE/appl_res/%L/%N:$TeleUSE/appl_res/%N:/usr/lib/X11/app-defaults/%L/%N:/usr/lib/X11/app-defaults/%N

LD_LIBRARY_PATH=$TeleUSE/lib:$OPENWINHOME/lib:/usr/lib:/usr/ucblib
PATH=$PATH:$OPENWINHOME/bin:$TeleUSE/bin:/usr/ucb:/usr/local/bin

umask 022

exec $APP >> $USERLOG
