#!/bin/csh

#
# Sets up appropriate ENV variables for running MEI in Production.
#
# All SQL transactions logged to USERLOG.
#

cd `dirname $0`

source Configuration

setenv DSQUERY	MGD_DEV
setenv MGD	mgd_release
setenv STRAINS	strains_release
setenv NOMEN	nomen_release

exec $EIINSTALLDIR/$EIAPP/$EIAPP >>& $USERLOG
