#!/bin/ksh

#
# Sets up appropriate ENV variables for running MEI in Production.
#
# All SQL transactions logged to USERLOG.
#

unset TERM
export APP USERLOG DSQUERY MGD STRAINS NOMEN EIREPORTDIR ARCHIVEDIR INSTALL_ROOT
export SYBASE OPENWINHOME PYTHONPATH
export XKEYSYMDB TeleUSE XNLSPATH XUSERFILESEARCHPATH LD_LIBRARY_PATH PATH

APP=mgd

cd `dirname $0`
INSTALL_ROOT=`pwd`

OPENWINHOME=/usr/openwin
XKEYSYMDB=$OPENWINHOME/lib/XKeysymDB
PYTHONPATH=/usr/local/lib/python1.4:/usr/local/etc/httpd/python

USERLOG=$HOME/.mgd-log

DSQUERY=MGD
MGD=mgd
STRAINS=strains
NOMEN=nomen

EIREPORTDIR=$HOME/mgireport
ARCHIVEDIR=$INSTALL_ROOT/$APP/mgireport

SYBASE=/opt/sybase
TeleUSE=/opt/teleuseXRT
XNLSPATH=$TeleUSE/X11R5/lib/nls
XUSERFILESEARCHPATH=%N:$OPENWINHOME/lib/app-defaults/%L/%N:$OPENWINHOME/lib/app-defaults/%N:$TeleUSE/appl_res/%L/%N:$TeleUSE/appl_res/%N:/usr/lib/X11/app-defaults/%L/%N:/usr/lib/X11/app-defaults/%N

LD_LIBRARY_PATH=$SYBASE/lib:$TeleUSE/lib:$OPENWINHOME/lib:/usr/lib:/usr/ucblib
PATH=$PATH:$OPENWINHOME/bin:$TeleUSE/bin:$SYBASE/bin:/usr/ucb:/usr/local/bin

umask 022

exec $APP >> $USERLOG
