#!/bin/csh

#
# Sets up appropriate ENV variables for running MEI in Production.
#
# All SQL transactions logged to USERLOG.
#

cd `dirname $0`

source Configuration

exec $EIINSTALLDIR/$EIAPP/$EIAPP >>& $USERLOG
