
/**************************************************************
 *
 * Name: uxb_mainc.c
 *
 *   File was generated by TeleUSE tool 'uxb_gcomp'
 *   -mode pcd
 *
 **************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>

#include <teleuse/teleuse.h>
#include <teleuse/tu_runtime.h>
#include <teleuse/tu_erhdlr.h>
#include <teleuse/tu_list.h>
#include <uxblib/uxb_uidef.h>
#include <uims/uf_uidef.h>
#include <wtlib/ux_pcdlib.h>
#include <teleuse/tu_eh_cvt.h>
#include <wrlib/ux_uiwid.h>

#ifdef _NO_PROTO
extern void ux_cbt_rtinit();

extern void ux_xt();
extern void ux_xm();
#else
#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
extern void ux_cbt_rtinit(void);

extern void ux_xt(void);
extern void ux_xm(void);
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
#endif /* _NO_PROTO */

#include <dtype/dt_rttype.h>
#include <drut/dl_type.h>
#include <drut/dr_runtime.h>

#ifdef _NO_PROTO
extern void ux_declare_busy();
extern void ux_declare_fork();
extern void ux_declare_uflib();
extern void ux_declare_wrlib();
extern void ux_declare_xm();
extern void ux_declare_xm_c();
extern void ux_declare_xt_c();
extern void ux_declare_tuw_c();
#else
#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
extern void ux_declare_busy(void);
extern void ux_declare_fork(void);
extern void ux_declare_uflib(void);
extern void ux_declare_wrlib(void);
extern void ux_declare_xm(void);
extern void ux_declare_xm_c(void);
extern void ux_declare_xt_c(void);
extern void ux_declare_tuw_c(void);
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
#endif /* _NO_PROTO */

#include <X11/Xlib.h>
#include <X11/Intrinsic.h>

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif

#if defined(__cplusplus) || defined(c_plusplus)
}
#endif

#ifdef _NO_PROTO
/* Application init functions defined by user */
extern int xrt_conv();
extern void ux_xrt();
#else /* _NO_PROTO */
#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
/* Application init functions defined by user */
extern int xrt_conv(int* argc, char** argv,
                    uxb_uidef_ptr uidef, Display *dpy);
extern void ux_xrt(void);
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
#endif /* _NO_PROTO */

#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
#ifdef _NO_PROTO
extern void uxb_mainc_declare_fl();
#else
extern void uxb_mainc_declare_fl(void);
#endif /* _NO_PROTO */
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif


/**************************************************************
 * uxb_mainc_init:
 **************************************************************/
#if defined(__cplusplus) || defined(c_plusplus)
extern "C" {
#endif
#ifdef _NO_PROTO
int uxb_mainc_init(argc, argv, phase, uidef_file)
     int* argc;
     char** argv;
     int phase;
     char* uidef_file;
#else
int uxb_mainc_init(int* argc, char** argv, int phase, char* uidef_file)
#endif /* _NO_PROTO */
{
  uxb_uidef_ptr uidef;
  Display* display;

  switch (phase) {
    case 0: /* PHASE 0 */
      /* Open the error & help database */
      (void) tu_eh_open_db((char*)"$TeleUSE/lib/teleuse.ehdb", (tu_eh_fih *)NULL);

      /* Register 'C:', 'D:' etc. */
      ux_cbt_rtinit();

      ux_xt();
      ux_xm();
      ux_xrt();

      /* initialize the pcd/widget interface routines */
      ux_init_pcd_mode();

      return 0; /* END PHASE 0 */

    case 1: /* PHASE 1 */
      /* Make converters known */
      tu_xt_resource_converters();
      tu_xm_resource_converters();
      tu_eht_resource_converters();

      /* Set up the predefined callbacks */
      tu_xt_callbacks();
      tu_xm_callbacks();

      /* Initialize predefined D types */
      dp_init_predef_types();

      /* Check that the file can be found */
      if (!uidef_file) {
        (void) fprintf(stderr, "\t%s\n",
          "Unable to locate user interface definition file");
        exit(1);
      }

      /* Read in the file */
      uidef = uxb_read_uidef(uidef_file, (char **)NULL);
      if (!uidef) {
        (void) fprintf(stderr, "\tUnable to parse user interface definition file '%s'\n", uidef_file);
        exit(1);
      }
      free((char*)uidef_file);
      /* load all pcd & pcq files ... */
      ux_load_pcd_list(tu_config_get_field(uidef,(char*)"PCD"),
                       tu_config_get_field(uidef,(char*)"PCDPATH"));
      ux_load_pcd_list(tu_config_get_field(uidef,(char*)"PCQ"),
                       tu_config_get_field(uidef,(char*)"PCQPATH"));

      /* set up paths to lookup images */
      ux_set_uidef_image_path(uidef);

      /* Application interface function declarations */
      ux_declare_uflib();
      ux_declare_wrlib();
      ux_declare_xt_c();
      ux_declare_xm_c();
      ux_declare_fork();
      ux_declare_busy();
      uxb_mainc_declare_fl();

      /* Load interpreted D modules */
      if (!dl_init_interpreter(uidef)) {
        fprintf(stderr, "Unable to load interpreted D modules\n");
        exit(1);
      }

      /* Call application initialization functions */
      display = tu_disp_get_dpy((char *)NULL);
      if (xrt_conv(argc, argv, uidef, display))
        exit(1);

      uxb_destroy_uidef(uidef);

      return 0; /* END PHASE 1 */

    default:
      return 0;
  }
}
#if defined(__cplusplus) || defined(c_plusplus)
}
#endif
