
# 
# Makefile to XRT authorize the new executable
# every time it is re-made.
# See uxb.conf
# 

all:	xrt_auth

xrt_auth: nomen
	$$XRTHOME/bin/xrt_auth nomen
	@echo xrt authentication done

clean::

delete::

install::
